### ISSUE TITLE
[Feature] Application Health Monitoring

### ISSUE THREAD

**Issue by jorisnoo** [webhub-works/craft-ohdear#21]
Hi there! I'm currently looking for a way to integrate [Application Health Monitoring](https://ohdear.app/feature/application-health-monitoring) with Craft websites. Is this something you'd consider providing with this plugin? I'd happily pay for it :)

**Comment by rostockahoi** [comment]
Hi, yes this is actually on our list. We hope to ship it in February. What metrics would you like to use?

**Comment by jorisnoo** [comment]
Great to hear! I'd find the following checks useful:
* **Craft Queue Worker is running**
* Application Cache
* **CPU Load**
* Database Connection
* Debug Mode
* Environment
* Redis
* **Used Disk Space**

**Comment by rostockahoi** [comment]
Hi there, we are currently working on a quite big update including:
- German translation
- performance monitoring
- health checks

We hope to ship it this week. However, I can tell right now that PHP ^8.0.0 will be required for that update.

**Comment by rostockahoi** [comment]
Hey @jorisnoo, we're almost there. I added a wiki page (https://github.com/webhubworks/craft-ohdear/wiki/Application-health-checks). You might want to take a look at the pre-release with `composer require webhubworks/craft-ohdear:dev-master`.

**Comment by rostockahoi** [comment]
The new release including health checks arrived. 🎉 Let me know if you get stuck.
