### ISSUE TITLE
Install issues, conflicting packages

### ISSUE THREAD

**Issue by arifje** [webhub-works/craft-ohdear#25]
I'm keep getting this, when installing;

```
  Problem 1
    - Root composer.json requires webhubworks/craft-ohdear 1.2.2 -> satisfiable by webhubworks/craft-ohdear[v1.2.2].
    - webhubworks/craft-ohdear v1.2.2 requires ohdearapp/ohdear-php-sdk ^1.6.0 -> found ohdearapp/ohdear-php-sdk[1.6.0, ..., 1.10.0] but it conflicts with your root composer.json require (^3.4).
   ```

But when I look in composer.json, it says it requires ohdearapp/ohdear-php-sdk ^3.4.0, so I am confused why this is not working.

How can I solve this?

**Comment by rostockahoi** [comment]
Hey @arifje, could you post the contents of your `composer.json`? The issue might be resolved by running the require command with a `-W` flag.

**Comment by rostockahoi** [comment]
@arifje Could you resolve the issue?

**Comment by arifje** [comment]
Hi @rostockahoi , this is my json: https://pastebin.com/VBP2Pvss

I tried -W, not working because of other required package versions like guzzle. 

<img width="1149" alt="Screenshot 2022-03-16 at 08 35 32" src="https://user-images.githubusercontent.com/1286410/158539493-a38c8af8-2971-4a40-843f-a6b3243c557f.png">

**Comment by rostockahoi** [comment]
There is a lot going on there. But this error seems to differ from the initial error message that you posted. Looks like guzzle is the issue now. Composer suggests a specific version to be installed in the last line. You might want to try that.
Another (brutal) way is to throw away the vendor dir and the composer lock file and to run `composer i` again.

Also: I saw that your app is running on PHP 7.4. In the next couple of days we'll release a new major version that requires PHP 8.

**Comment by arifje** [comment]
I will give it a try! 

I also updated to PHP 8.1 this week, so that shouldn't be an issue.

**Comment by rostockahoi** [comment]
I'll close this for now.

**Comment by arifje** [comment]
Update: tried to install that specific guzzle version, but then I ran into this;

```
  Problem 1
    - php-http/guzzle7-adapter 1.0.0 requires guzzlehttp/guzzle ^7.0 -> found guzzlehttp/guzzle[dev-master, 7.0.0-beta.1, ..., 7.4.x-dev (alias of dev-master)] but it conflicts with your root composer.json require (6.5.x-dev).
    - craftcms/mailgun 2.0.0 requires php-http/guzzle7-adapter ^1.0 -> satisfiable by php-http/guzzle7-adapter[1.0.0].
    - craftcms/mailgun is locked to version 2.0.0 and an update of this package was not requested.
    ```

**Comment by rostockahoi** [comment]
Is it an option for you to throw away the Composer lock file, remove the vendor directory and then reinstall? Let's see if that solves the issue.

This gives Composer the opportunity to determine possible versions from scratch. You would likely end up with slightly different versions throughout the packages though.

(I wanted to try it by myself but I don't have all your local repositories in place.)

**Comment by arifje** [comment]
Well, I think I got it working. Pain in the ass, all these packages 😂

I had to remove some old packages, because I also got this after deleting/reinstalling;

```
  Problem 1
    - Root composer.json requires webhubworks/craft-ohdear ^2.0 -> satisfiable by webhubworks/craft-ohdear[2.0.0].
    - webhubworks/craft-ohdear 2.0.0 requires symfony/process ^5.4|^6.0 -> found symfony/process[v5.4.0-BETA1, ..., 5.4.x-dev, v6.0.0-BETA1, ..., 6.1.x-dev] but these were not loaded, likely because it conflicts with another require.
   ```
I removed an old facebook sdk, and some other stuff. Then it installed.

Thanks for the help!
