### ISSUE TITLE
Health Report URL seems broken in headless mode

### ISSUE THREAD

**Issue by jorisnoo** [webhub-works/craft-ohdear#28]
Hi there!

I've just given the new version a try — unfortunately, there seems to be an issue with the health report endpoint on `/ohdear/api/health-check-results` with the following settings in `config/general.php`:

```
'cpTrigger' => null,
'headlessMode' => true,
```

Are you able to reproduce this issue? Thanks a lot!

**Comment by rostockahoi** [comment]
Hi, let me look into it.

**Comment by rostockahoi** [comment]
@jorisnoo I am able to reproduce. But I am still a bit lost to find the reason. Do you have any other plugins running in that setup that also implement API routes that still work?

**Comment by rostockahoi** [comment]
@jorisnoo I think I fixed the issue with Tag 2.0.1  While I am going to update the Wiki, you can use the following URL to receive the App Health Checks: `/actions/ohdear/health-check/results`

Just paste it into the Oh Dear App Health Settings and it should be fine.

**Comment by jorisnoo** [comment]
Awesome, thank you!
