### ISSUE TITLE
Does not support `cpTrigger`, `admin` is hard-coded in Check.js

### ISSUE THREAD

**Issue by Saboteur777** [webhub-works/craft-ohdear#3]
See https://github.com/webhubworks/craft-ohdear/blob/master/src/assetbundles/ohdear/src/js/resources/Check.js#L45

If the site uses different [`cpTrigger`](https://craftcms.com/docs/3.x/config/config-settings.html#cptrigger) than admin, these will result in broken links in the CP.

**Comment by rostockahoi** [comment]
Thank you for your request. I'll look into it. I guess there are some more places that have to be adjusted.
