### ISSUE TITLE
Feature request: Granular Permissions

### ISSUE THREAD

**Issue by jorisnoo** [webhub-works/craft-ohdear#30]
Hi (it's me again!) 😄 

It was great to see the latest addition to the plugin. To take full advantage of the plugin, I'd like to give clients access to the plugin in the CP. Ideally, however, they should not be able to activate or deactivate checks — which seems currently possible with the toggles on the overview screen.

Would you consider adding a permission for enabling/disabling checks - or for viewing certain plugin pages (like overview, uptime. etc.)?

Thanks a lot for your effort!

**Comment by rostockahoi** [comment]
Seems like a decent feature. Let me look into it.

**Comment by jorisnoo** [comment]
My current "solution" is to simply hide the toggles:
```
#ohdear-app .lightswitch-field {
    display: none;
}
```

**Comment by rostockahoi** [comment]
There is a new release 4.1.0 introducing granular permissions. How it works for you.

**Comment by jorisnoo** [comment]
@rostockahoi Thanks!
