### ISSUE TITLE
Broken Links to Reports in Headless Mode

### ISSUE THREAD

**Issue by jorisnoo** [webhub-works/craft-ohdear#40]
Hi again :)
When running Craft in headless mode, the `cpTrigger` config is set to `null`. Unfortunately, opening the different reports from the Overview panel does not work, as the links are set to eg. `/null/ohdear/uptime` instead of `/ohdear/uptime`:

https://github.com/webhubworks/craft-ohdear/blob/ee78bb7a9dccf64a8ae8943675ca6bfee8dfe6e4/src/assetbundles/ohdear/src/js/resources/Check.js#L49

Thank you for all your effort on this plugin!

**Comment by rostockahoi** [comment]
Hey there, sorry for the delay.

To reproduce, do I only have to set cpTrigger to null and that's it?

**Comment by jorisnoo** [comment]
Yes, i think that should suffice to reproduce the issue. I'm using the following settings in general.php:

```
->cpTrigger(null)
->headlessMode()
```

**Comment by rostockahoi** [comment]
There is a new release 4.1.0 fixing the nullable cpTrigger issue. How it works for you.
