### ISSUE TITLE
Feature request: Any plans to include other checks?

### ISSUE THREAD

**Issue by stevecomrie** [webhub-works/craft-ohdear#42]
- Lighthouse
- Scheduled Tasks
- DNS
- Domain

?

**Comment by rostockahoi** [comment]
Hey there, which one would you like the most?

**Comment by stevecomrie** [comment]
Lighthouse would probably be the most impactful to see frequently at a glance.

**Comment by rostockahoi** [comment]
I am releasing a couple of changes shortly. After that I'll take a look at it.

**Comment by rostockahoi** [comment]
@stevecomrie The new plugin version for Craft 5 has been released and it includes a new Lighthouse check. I'll put the other checks into the roadmap and close this ticket for now.
