### ISSUE TITLE
Feature request: Number of Broken Links indicator

### ISSUE THREAD

**Issue by jorisnoo** [webhub-works/craft-ohdear#46]
Hi there 👋 
I've noticed that editors started to look at the broken links since they have access to the plugin, which is great.
This made me wonder whether you'd consider adding a badge/indication if some tests are failing (personally i'd mostly be interested in showing the number of broken links) to draw more attention to it?

<img width="75" alt="Screenshot 2023-07-31 at 20 57 49" src="https://github.com/webhubworks/craft-ohdear/assets/5810772/8daa1123-23a5-4fde-bb09-a961b18addf2">

Thanks for your consideration and continued work on this plugin!

**Comment by rostockahoi** [comment]
Well, why didn't I think about that? 😀

Let me try that. It requires the ability to add a badge to sub nav items also.

**Comment by rostockahoi** [comment]
Will be released in the upcoming. However, I had to cache the requests. The feature will be activatable via settings.
