### ISSUE TITLE
Permissions Object in Frontend

### ISSUE THREAD

**Issue by jorisnoo** [webhub-works/craft-ohdear#47]
Hi there!
I'd just noticed that the following snippet appears in the source code of my frontend; even if no user is logged into Craft:
```
window.OhDear = window.OhDear || {};
window.OhDear.permissions = window.OhDear.permissions || {};
```

Of course this is not really an issue, just a matter of aesthetics maybe :-) What i like about Craft, eg. compared to WordPress, that there is not a bunch of plugins adding JS snippets to the frontend.

As always, thanks a lot for your work!

**Comment by rostockahoi** [comment]
Thanks for the hint. What would man be without the aesthetics?

Fixed in the upcoming release.
