### ISSUE TITLE
[Feature] Allow customizing the plugin name

### ISSUE THREAD

**Issue by michaelhue** [webhub-works/craft-ohdear#57]
One of the strengths of this plugin is the fact that clients can check the **Oh Dear** metrics themselves in the Control Panel. But the name **Oh Dear** is not very intituitive as displayed in the CP navigation and page titles. It would be nice to be able to configure the plugin name to something more sensible, like **Monitoring** or **Status**.

Plugins like [Formie](https://verbb.io/craft-plugins/formie/docs/get-started/configuration#configuration-options) have this option and I think it would be a nice additon for this plugin as well.

Thanks and kind regards from Hannover!

**Comment by rostockahoi** [comment]
Hey there, thanks for the feedback. Let me put this item on the roadmap.

**Comment by rostockahoi** [comment]
Hey there, we tagged a new release with v4.5.0 that includes this feature.
